### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by k4waiiiii** [ShinyQ/Final-IFest-2021_Analisis-Sentimen-Kebijkakan-PPKM-Pemerintah#1]
Apakah datanya boleh saya pakai untuk keperluan skripsi?

**Comment by ShinyQ** [comment]
Halo, silahkan boleh.

**Comment by k4waiiiii** [comment]
Terima kasih. Sekalian mau nanya, itukan habis crawling/scrapping datanya dilabelin negatif/netral/positif sebelum diproses dan datanya banyak banget. Itu pelabelan kalo boleh tau gimana caranya ya?
